language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
before_install:
- export TZ=Pacific/Noumea
install: mvn -DcreateChecksum=true clean install
env:
  global:
  - secure: kS4FZrxWIHNvAL9EcMjSE97A7Tt+sbeoVTgX+xcqdy8QOc10DUW+TzCEmxj1GZcpQWR6R0JHn1tpyzQ4/wiqUuKrkSESqm7TE2Ch88xrE40txvVlzvNEXf6QRPC4nwJdFlciheYP6aWesrnrnHbwhHMNC9DyfC0jMLh0aM+/LvjCmZkhTzYjmiMW/ZupFCrPrtLJ0cqyAXFbanwnjaU7VJM9jTGEJBb/Na8gvdrUzNnu9uPP3v/59zx/WS04eak2bl1/xkLdZD4GJZmMdbGXJv0Ec86Nmzg/hh60j6DKEtxFL+CRwsHXPXfMumVDUCOG+WaT4c65uF2e62gw9ryUab6scnPcNXukDD7lmvVVjrGKa/UGagrJ4QPvQ0JIQO1euzo+VilHtIV1Lvxqaktze0LYWVcdBHPd6D44eXFXJMbHbHkvoyjFnaIAM36+WiUKdQjWklT4+MDlOpEXf7L+V4jBMaFtpZh9h9Q9dAwIKoxVUvW7PML1fzD/nSrxLpjCjzzevwce0ObjKeTrhyuNHnXMkye5a3PB0TrvBzLfXFsXxhCX5zoYw8EHR8q7pySyMlQKNEe+u+HKhYlY6GUoJkB9H1wfrz81eepBZegW3fOtuUcEjvGnnwk9E9noq34XTr69K8LdIZUAfsL2b1o5n9/1Apcf7a457uFsNKpfGMU=
script:
- mvn test jacoco:report org.jacoco:jacoco-maven-plugin:prepare-agent
  install
after_success:
- mvn coveralls:report
before_deploy:
- export RELEASE_PKG_FILE=$(ls target/*.war)
- export RELEASE_PKG_MD5_FILE=$(ls target/*.war.md5)
- export RELEASE_PKG_SHA_FILE=$(ls target/*.war.sha1)
- echo "deploying $RELEASE_PKG_FILE , $RELEASE_PKG_MD5_FILE , $RELEASE_PKG_SHA_FILE to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: msjPaYs0dM/PW6vvzcdEbgG9RHPQ47C7zfssUTtBKhVuNA/vh32i5w/dw01tqJBlVX3DBjUUTyizczS7fULo0F9RkczDXNdoa0F+rfH01NGkp3eqPFmuE9javnSy+PhbafOmlPZbx/QMkkM1x8fbsu8kkMIZmmIb+y/VGtS1fqweZOJTPsHMvBxd6i42tMKYZZgcInARB5cCbvkyoRg7XdL3LKpQccl4YOBu6e0jFmpPby7sMueZwIVv47BqkOjqME6tqBG6X3BtdrT72MaOoH59lDnZFuj006JN85T65dHpP1qDapdd0usHH6242HblEtJqkRXS/9EMuZLvkbJUHaaGPnOmtVXBMYRTOkJSSZ7cw2/KtLQK4mMHFto/GR58K9rGyNrEfrx1sFHLQeZiZmr3/DsUgxvueQFyrVeU1ONefLxera4jFpyEwHHs4x7434pBOJfAyn1aA2Lj4jNvEdxNqWAbDp7UDBhRPoEDbLA8zsxu2fEpfVzN7wfviw94/UF591NFMPlxJ7CGUaK/ht5Xn8c68dHZjpO6eZo6pZvQ45BIN0F1ZFD248w4f/49n3jlwaxtubFSZvPVpCjZi+4Zu1U3CcYI1+l6GWS9CzF3x6y2DHxP2tLNjzAhg7fMhMHFWZkcauUhnm0a9FF3rPzW/UEka3JYz/0a7As+0sw=
  file:
  - ${RELEASE_PKG_FILE}
  - ${RELEASE_PKG_MD5_FILE}
  - ${RELEASE_PKG_SHA_FILE}
  skip_cleanup: true
  on:
    tags: true
    repo: DSI-Ville-Noumea/sirh-ws
notifications:
  slack:
    secure: Gt/HcHPVwTP6ReZqlDriQMTnPgoJSAE/+GQ94ssKvaikiuvnUZn0wlmn/Kmj48JUXNLizSmACreW+Yx7l/q2pXfFyQtXPxh4CLX37UBrMPAoYrRccvV10wrWK9XRMRd8+aBw1CT4Z5hsON0hpuHho/hMtuZw/QnenZfwUfgZ2t3lqWMp61VQlv+ZaY9i4vdkQfbkUCltdD2dMIp7Fl8ru+sJC59H5gadQbSPjky2NxPjyYDmOWWjdjGow9miVZ8q9uQ7afG8nGXIYUn8uwXBvbU3ZNMnntuHAsHkehKvB3vT9e9IoakTtlDGez0PQ8XKJXRoMQyNiv98yL2d1vnvAwi6pvLn6FSwWOq6K7m+6HBxN3a6WHHKIygokzsg5/+DgM3iocUJ6q20jhbcleMeDiefwbNjghH+hDcMAE3hv/4sA3jE3S3B5hnfGE5NwyIUAE+ncSIfkqHJefr5AAasC2q18SJyYLEoW0iLi78fHePic3rP1HSJyQuNFcVdZ8dxuWFTKCD1Dn2VzkBu/i2nQ9ZNUIDXkwh8HfsIjEDtsbcfhnGuJOIsV9i79MwVsT1+a07c45a/YHh0cvVRRiLG2hj41ruW/0HCwRFtoZF/5VWbO1Vxwo31PJG4ywgM7D1XGTVyucjbAD4n14JPbHyLCONxOMipqB9cgs+jjtKw/Hc=

