language: java
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2
before_install:
- export TZ=Pacific/Noumea
install: mvn -DcreateChecksum=true clean install --settings target/travis/settings.xml
env:
  global:
  - secure: kS4FZrxWIHNvAL9EcMjSE97A7Tt+sbeoVTgX+xcqdy8QOc10DUW+TzCEmxj1GZcpQWR6R0JHn1tpyzQ4/wiqUuKrkSESqm7TE2Ch88xrE40txvVlzvNEXf6QRPC4nwJdFlciheYP6aWesrnrnHbwhHMNC9DyfC0jMLh0aM+/LvjCmZkhTzYjmiMW/ZupFCrPrtLJ0cqyAXFbanwnjaU7VJM9jTGEJBb/Na8gvdrUzNnu9uPP3v/59zx/WS04eak2bl1/xkLdZD4GJZmMdbGXJv0Ec86Nmzg/hh60j6DKEtxFL+CRwsHXPXfMumVDUCOG+WaT4c65uF2e62gw9ryUab6scnPcNXukDD7lmvVVjrGKa/UGagrJ4QPvQ0JIQO1euzo+VilHtIV1Lvxqaktze0LYWVcdBHPd6D44eXFXJMbHbHkvoyjFnaIAM36+WiUKdQjWklT4+MDlOpEXf7L+V4jBMaFtpZh9h9Q9dAwIKoxVUvW7PML1fzD/nSrxLpjCjzzevwce0ObjKeTrhyuNHnXMkye5a3PB0TrvBzLfXFsXxhCX5zoYw8EHR8q7pySyMlQKNEe+u+HKhYlY6GUoJkB9H1wfrz81eepBZegW3fOtuUcEjvGnnwk9E9noq34XTr69K8LdIZUAfsL2b1o5n9/1Apcf7a457uFsNKpfGMU=
  - secure: vk1X7idpD81rPq8rcHGG1PFkV/xq0AKhHh8/8zUFc26mOlV3Jrk+fSydYHswx72yO9iYfW65CRYyEyx3qirpayPDiO7u0zsXw9V9MSbJi/XHBjD9iNuy4cN/T8DNoB3zYjTOVUJNGVWAaVaWG0mcPAr9hATACCn95s0Rpkrd4YWqde2oJl1E7/nlGGhdS6mSvm1aV4NxuSlPL+IZwEjYurzcz0/F8YENy0ZLZKFfyVohIMuXeObNfMVzyRK/WFwD+Rja4uWjYiz+Iqcv7Zh6UmMInObffnb8FNKTFHot7IrceQwobMGfqBMyjMaed+7ZmyycfLo6k5J1kJ+LO8Th0Vsu0AzdhXFhjtaAKtwY+GbmkhiLCSvQqNLaMT6bWdPI/ktKbQxvrHN5YFlNiN4yBWzdJGemPKFQgH0QXbCGphLsPQOUuvM8aE2F7G6od/fsf5tNRL/4fsEXfOsMhAFl3x89o696PTDfal20bYSthCcAspwWec7uSi+aVdljLf50Jmn5ynwypNaVoeP8Z9z1cyrjqWs9nXcUQBilLuDt4SmKTvVgK9uCdIhG61jOzYc2L6pat0ZUio3ZWp7PQBXeAnxVqt4/g30bw/WcjAyB5BV6FnuRkn6YUyzNKb4wG560xGcnEfO6kH9Xmcj/iFuplRRaBJZPfGrYXKptuh7HsiU=
  - secure: GrMLJ7uH61FHH3q6nqvsxUApJWIfaZaaEuSDbXbDD8kLe3FGOr5Dgxw7P2yQeDKEzE2d9U9CjHsAkS8qH0NVox+f3HizJsErIzr0QvN47oTbqwttI6ax54yUpDr9ESUdfnKFvtcifkanRYs+CSYFmG3GHQZSttK3En7xnJ0+sVUmsv17U+mJsafJeWPsvERG1R9kOBdCNanHE0jyLQmADc+Hj5VM++3pXFsG51kk83QRQSY2kSfMr4OOaJ6LGe6gk+1LRu65OdNHDVbczN/zv6YlQD8iDJ4yxg45fmt1Dzj8e+XtCmZv3xSdxxWDVn1fpO7ugFxnrGlRAJFSzkMD0KtXRzXcrt90+bU19G/w14QYHZCujpSjMEw0oLbzn+/RdpI7xEmgTiUKypMjWmzQ873xaGY5fX8mJqOnrli6ZmNWL+EnxYqjmfm8zqFCIXEWManabvWSe0y9LrTJPrm1mLdzpYmKiOtqFP2TOeJrEN15Fwl9YjaXFOQn/XPI8qTBMXXQRigsNbyQB14XI5Z81zyEyOpuEOOQUj7q1y2tLJ1eoRkzCUvRfyGXz3cjX6l5YrjIj8bP1v33wObO0nK+/LBly/OiPH41Ik7TnahhDHE25GHT+4YpsWyesUQPXSK6uh/uUB/3X8YtxiZ7hmbF4ii0cQ2dgyX7nY8g/fRhh0w=
script:
- mvn versioneye:update test jacoco:report
after_success:
- mvn coveralls:report
before_deploy:
- export RELEASE_PKG_FILE=$(ls target/*.war)
- export RELEASE_PKG_MD5_FILE=$(ls target/*.war.md5)
- export RELEASE_PKG_SHA_FILE=$(ls target/*.war.sha1)
- echo "deploying $RELEASE_PKG_FILE , $RELEASE_PKG_MD5_FILE , $RELEASE_PKG_SHA_FILE to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: iKWcrDJTfNKQVNyQdQYXUH+Q1cBLhPriDInGHvAH4EoBvZChOn7l121b/AdIwvjaaU90ljLw9CiNjHawVi584oaQ5A1ezs98Z2qMmcDg+0pAVoH3wcwin13lnpiYGhSi9jd+wt7P7gRfyniBkR9mqfmOhw07tTNJ9rsZQyRYUvBs5pcyDqjZ6Zjt6e1Y3xO+FmvPAv7LJ4L49oLnMxduuYIDDNA//2OPwcb9qn19NzSBeElKqmWAyVAu2ctA+oox3ARBzhTnOhU85AOJWsokuJBcSqw5Z7no6pIqz2+1PryOeEeXiQyZBL+Hx0TiivNQZnt5VsasWHjjVAooJMxmlcP4xP2NcP1DiiLiztFBeS6OuaSg9G7XNQUXMJzxP2ikZD1e7SyNJuzJNfRDDS8/fHn3qXC+wwpHsQ9a6CEUkvJlFsKD91gTutxX9lO/uSA9eRsHS5UNIn2LBI1WSH/bIwZnLPYHL+RbPWETga3CvouTADTS88elz40HI9qT7QVdMzrQrmg7+z9niiwV2HpVndPjF00oib4Akm2YWwEe35J24RB24Bfs8BcRE/4EWPdbMn4v6XyfaLM3VaCOCHKUUajn0dm34lwAIcTvmnKUN3maYdoXW6aGmu8uoVib8fil1uPlp27Ku2DRXme4vk4Rdw2thawuE59H8f+btz6FwI0=
  file: 
  - ${RELEASE_PKG_FILE}
  - ${RELEASE_PKG_MD5_FILE}
  - ${RELEASE_PKG_SHA_FILE}
  skip_cleanup: true
  on:
    tags: true
    repo: DSI-Ville-Noumea/sirh-ws
notifications:
  slack:
    secure: Gt/HcHPVwTP6ReZqlDriQMTnPgoJSAE/+GQ94ssKvaikiuvnUZn0wlmn/Kmj48JUXNLizSmACreW+Yx7l/q2pXfFyQtXPxh4CLX37UBrMPAoYrRccvV10wrWK9XRMRd8+aBw1CT4Z5hsON0hpuHho/hMtuZw/QnenZfwUfgZ2t3lqWMp61VQlv+ZaY9i4vdkQfbkUCltdD2dMIp7Fl8ru+sJC59H5gadQbSPjky2NxPjyYDmOWWjdjGow9miVZ8q9uQ7afG8nGXIYUn8uwXBvbU3ZNMnntuHAsHkehKvB3vT9e9IoakTtlDGez0PQ8XKJXRoMQyNiv98yL2d1vnvAwi6pvLn6FSwWOq6K7m+6HBxN3a6WHHKIygokzsg5/+DgM3iocUJ6q20jhbcleMeDiefwbNjghH+hDcMAE3hv/4sA3jE3S3B5hnfGE5NwyIUAE+ncSIfkqHJefr5AAasC2q18SJyYLEoW0iLi78fHePic3rP1HSJyQuNFcVdZ8dxuWFTKCD1Dn2VzkBu/i2nQ9ZNUIDXkwh8HfsIjEDtsbcfhnGuJOIsV9i79MwVsT1+a07c45a/YHh0cvVRRiLG2hj41ruW/0HCwRFtoZF/5VWbO1Vxwo31PJG4ywgM7D1XGTVyucjbAD4n14JPbHyLCONxOMipqB9cgs+jjtKw/Hc=