// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.model.pk;

import nc.noumea.mairie.model.pk.CadreEmploiFPPK;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect CadreEmploiFPPK_Roo_Configurable {
    
    declare @type: CadreEmploiFPPK: @Configurable;
    
}
