// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.model.pk;

import java.io.Serializable;
import nc.noumea.mairie.model.pk.ParentEnfantPK;

privileged aspect ParentEnfantPK_Roo_Serializable {
    
    declare parents: ParentEnfantPK implements Serializable;
    
}
