// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.model.bean;

import java.io.Serializable;
import nc.noumea.mairie.model.bean.Agent;

privileged aspect Agent_Roo_Serializable {
    
    declare parents: Agent implements Serializable;
    
    private static final long Agent.serialVersionUID = 1L;
    
}
