// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.model.bean;

import nc.noumea.mairie.model.bean.AgentRecherche;

privileged aspect AgentRecherche_Roo_JavaBean {
    
    public Integer AgentRecherche.getNomatr() {
        return this.nomatr;
    }
    
    public void AgentRecherche.setNomatr(Integer nomatr) {
        this.nomatr = nomatr;
    }
    
    public String AgentRecherche.getNomUsage() {
        return this.nomUsage;
    }
    
    public void AgentRecherche.setNomUsage(String nomUsage) {
        this.nomUsage = nomUsage;
    }
    
    public String AgentRecherche.getPrenomUsage() {
        return this.prenomUsage;
    }
    
    public void AgentRecherche.setPrenomUsage(String prenomUsage) {
        this.prenomUsage = prenomUsage;
    }
    
}
