// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.model.bean;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import nc.noumea.mairie.model.bean.AgentRecherche;

privileged aspect AgentRecherche_Roo_Jpa_Entity {
    
    declare @type: AgentRecherche: @Entity;
    
    declare @type: AgentRecherche: @Table(name = "AGENT");
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "ID_AGENT")
    private Integer AgentRecherche.idAgent;
    
    public Integer AgentRecherche.getIdAgent() {
        return this.idAgent;
    }
    
    public void AgentRecherche.setIdAgent(Integer id) {
        this.idAgent = id;
    }
    
}
