// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.model.bean;

import nc.noumea.mairie.model.bean.AvisCap;

privileged aspect AvisCap_Roo_JavaBean {
    
    public String AvisCap.getLibLong() {
        return this.libLong;
    }
    
    public void AvisCap.setLibLong(String libLong) {
        this.libLong = libLong;
    }
    
}
