// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.model.bean;

import java.io.Serializable;
import nc.noumea.mairie.model.bean.CadreEmploi;

privileged aspect CadreEmploi_Roo_Serializable {
    
    declare parents: CadreEmploi implements Serializable;
    
    private static final long CadreEmploi.serialVersionUID = 1L;
    
}
