// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.model.bean;

import nc.noumea.mairie.model.bean.Diplome;

privileged aspect Diplome_Roo_JavaBean {
    
    public String Diplome.getLibDiplomen() {
        return this.libDiplomen;
    }
    
    public void Diplome.setLibDiplomen(String libDiplomen) {
        this.libDiplomen = libDiplomen;
    }
    
}
