// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.model.bean;

import nc.noumea.mairie.model.bean.Enfant;

privileged aspect Enfant_Roo_JavaBean {
    
    public String Enfant.getNom() {
        return this.nom;
    }
    
    public void Enfant.setNom(String nom) {
        this.nom = nom;
    }
    
}
