// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.model.bean;

import java.io.Serializable;
import nc.noumea.mairie.model.bean.NatureAvantage;

privileged aspect NatureAvantage_Roo_Serializable {
    
    declare parents: NatureAvantage implements Serializable;
    
}
