// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.model.bean;

import nc.noumea.mairie.model.bean.Sicomm;

privileged aspect Sicomm_Roo_JavaBean {
    
    public String Sicomm.getLibVil() {
        return this.libVil;
    }
    
    public void Sicomm.setLibVil(String libVil) {
        this.libVil = libVil;
    }
    
}
