// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.model.bean;

import nc.noumea.mairie.model.bean.Silieu;

privileged aspect Silieu_Roo_JavaBean {
    
    public String Silieu.getLibelleLieu() {
        return this.libelleLieu;
    }
    
    public void Silieu.setLibelleLieu(String libelleLieu) {
        this.libelleLieu = libelleLieu;
    }
    
}
