// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.model.bean;

import nc.noumea.mairie.model.bean.Siserv;

privileged aspect Siserv_Roo_JavaBean {
    
    public String Siserv.getLiServ() {
        return this.liServ;
    }
    
    public void Siserv.setLiServ(String liServ) {
        this.liServ = liServ;
    }
    
}
