// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.model.bean;

import nc.noumea.mairie.model.bean.Sivoie;

privileged aspect Sivoie_Roo_JavaBean {
    
    public String Sivoie.getLiVoie() {
        return this.liVoie;
    }
    
    public void Sivoie.setLiVoie(String liVoie) {
        this.liVoie = liVoie;
    }
    
}
