// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.model.bean;

import nc.noumea.mairie.model.bean.Spgeng;

privileged aspect Spgeng_Roo_JavaBean {
    
    public String Spgeng.getLiGrad() {
        return this.liGrad;
    }
    
    public void Spgeng.setLiGrad(String liGrad) {
        this.liGrad = liGrad;
    }
    
}
