// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.model.bean;

import nc.noumea.mairie.model.bean.TypeContact;

privileged aspect TypeContact_Roo_JavaBean {
    
    public String TypeContact.getLibelle() {
        return this.libelle;
    }
    
    public void TypeContact.setLibelle(String libelle) {
        this.libelle = libelle;
    }
    
}
