// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.model.bean.eae;

import nc.noumea.mairie.model.bean.eae.Eae;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Eae_Roo_Configurable {
    
    declare @type: Eae: @Configurable;
    
}
